### ISSUE TITLE
O MELHOR DOS MELHORES

### ISSUE THREAD

**Issue by c0destep** [DevPedroDev/OlimpiadaPrograma-o-12horas#1]
### Agradecimentos

Quero agradecer a oportunidade de trabalhar ao lado de um Dev que inspira gerações, sem medo de se arriscar em tendencias ele se joga no código. Satisfação esta ao seu lado @DevPedroDev .

**Comment by DevPedroDev** [comment]
É isso irmão! Muito gratificante participar dessa maratona junto com você, grande aprendizado para ambos. Conseguimos entregar um pouquinho desse mundo tão vasto que é a programação. Valeu @c0destep a medalha dessa vez foi nossa
